language: go

go:
  - 1.7
  - 1.8
  - tip

script: 
  - go build 
  - go install
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false