language: go

go:
  - 1.7
  - 1.8
  - tip

script: 
  - go get github.com/mathieunls/golr/engine
  - go get github.com/mathieunls/golr/solrjson
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false